version: '3'
services:
  ipfs_server:
    build:
      context: ./IpfsServer
    ports:
      - '4001:4001'
      - '5001:5001'
      - '8080:8080'
      - '8081:8081'
      - '54000:54000'
    container_name: ipfs_server

  geth_signer:
    build:
      context: ./GethSigner
    ports:
      - '8545:8545'
      - '8546:8546'
      - '30301:30301'
      - '30303:30303'
      - '54001:54001'
    container_name: geth_signer

  server:
    build:
      context: ./Server
    ports:
      - '54002:54002'
    container_name: server
